# Generated by Django 4.1 on 2022-08-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='apt_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
